### ISSUE TITLE
new values for Songbird Sources 

### ISSUE THREAD

**Issue by lukemunn** [google/songbird#1]
I'm trying to setup 'multiple' rooms, by changing the sounds and room sizes when certain triggers are hit. 

Changing the room dynamically works well, setting new Materials and Dimensions.

But swapping out the sounds (sources) and their properties doesn't seem to work. My idea was to setup the DOM just one time with an array of generic AudioElements etc. Then, each time the room changes, update the mp3 URL, the Gain, the Maximum Distance, etc. The sounds do get added into the Room but they're all equally loud, like they're just 'inheriting' the properties from the previous generic setup. 

If you try to create new Sources and splice them into the AudioSources array, any sourceOptions you feed them are ignored (e.g. I tried setting Gain and Max distance to 0).  

So for now I've resorted to creating a new Songbird instance each time, a new array of AudioElements, AudioSources, etc, but I can't imagine this is good for memory or the ideal approach. 

Ideally Sources would have the same method as a Room, e.g. SetSourceProperties(maxDist, gain, etc etc). 

Any help appreciated. :-)

**Comment by drewbitllama** [comment]
Also, you can change the source's properties directly but yes, we should expose the individual properties like you mention. I'll do that when I return to work. :) (Currently on a week vacation).

**Comment by lukemunn** [comment]
Thanks for response (on your holiday no less). ;-)

The code I'm working with now is a mess so I've done a new minimal test showing what happens, based on your room model example.  

Just realized that the Inspector shows the values (e.g. position, maxdist) do in fact change, but there is no change in the audio.

But I'm not really a programmer, so I could very well be missing something obvious. Any help appreciated.

`var songbird;
    // Define source audio files.
    var audioSources = [
      'resources/CubeSound.wav', 'resources/SpeechSample.wav'
    ];


    // This is used to scale the appropriate dimension.
    var materials = {}
 	var dimensions = {
      width : 4,
      height : 4,
      depth : 4
    }


    var audioElements = [];
    var songbirdSource = [];
    var audioElementSources = [];
    var context;
    
    var onLoad = function () {

      context = new AudioContext();
      audioElementSources = Array(audioSources.length);

      // Create <audio> streaming audio sources.
      for (var i = 0; i < audioSources.length; i++) {
        audioElements[i] = document.createElement('audio');
        audioElements[i].src = audioSources[i];
        audioElements[i].load();
        audioElements[i].loop = true;
        audioElements[i].play();
        audioElementSources[i] =
          context.createMediaElementSource(audioElements[i]);
      }

      // Initialize Songbird and create Source(s).
      songbird = new Songbird(context, {
        ambisonicOrder: 3,
        dimensions: dimensions,
        materials: materials
      });
      for (var i = 0; i < audioSources.length; i++) {
        songbirdSource[i] = songbird.createSource();
        audioElementSources[i].connect(songbirdSource[i].input);
      }
      songbird.output.connect(context.destination);

    };
    
    // ini basic songbird with two sources
    window.addEventListener('load', onLoad);
    
    
    function updateSources() {
   	
    	for (var i = 0; i < audioSources.length; i++) {
    		
    		// way #1, alter properties directly
    		songbirdSource[i].maxDistance = 0.1;
    		console.log(songbirdSource[i]);
    		// way #2, create new sources and put in old array
    		 var sourceOptions = {
			  position: [-3, 0, 3],
			  forward: [0, 0, -1],
			  up: [0, 1, 0],
			  minDistance: 0.1,
			  maxDistance: 0.1,
			  rolloff: 'logarithmic',
			  gain: 0,
			  alpha: 0,
			  sharpness: 1,
			  sourceWidth: 0
			}
    		
    		songbirdSource[i] = songbird.createSource(sourceOptions);
    		console.log(songbirdSource[i]);
    	}
    	
    	
    }
    
    // now update sources
    setTimeout(updateSources, 2000);`

**Comment by drewbitllama** [comment]
Hi Luke,

Currently, songbird sources don't allow the direct updating of attenuation parameters like minDistance via the way you're trying to invoke (in fact, the property .minDistance is being created in your code, but this is because the assumed use case for minDistance/maxDistance/gain/etc. will be mostly constant over the lifetime of the source. To change the sound quality, you should adjust the position (via source.setPosition() which does most of the heavy lifting to change where the sound appears to come from. Also, you'll want to use songbird.setListenerPosition() to change the position of the listener as well, and the relationship between the source position, listener position and their relative positions in the room (which is centered around the origin 0,0,0) produce the overall effect. 

For more detailed information about how the current API works, please consult the documentation: https://cdn.rawgit.com/google/songbird/master/doc/index.html

If there are still functions you feel would benefit you outside of the those provided, we can certainly consider introducing them.
