### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_3_songbird_audio___default.a is not a constructo

### ISSUE THREAD

**Issue by NicholasLYang** [google/songbird#5]
Getting a very annoying error when trying to use songbird. Basically the Songbird object is not a constructor. I'm pretty much just using the demo code with some minor ES6 changes (var to let). Any idea why this is happening?
```
   let audioContext = new AudioContext();
    let songbird = new Songbird(audioContext);
    songbird.output.connect(audioContext.destination);
    let dimensions = {
      width : 3.1,
      height : 2.5,
      depth : 3.4
    };
    let materials = {
      left : 'brick-bare',
      right : 'curtain-heavy',
      front : 'marble',
      back : 'glass-thin',
      down : 'grass',
      up : 'transparent'
    };
```

**Comment by drewbitllama** [comment]
Hi Nicholas,

I'm planning to push a new commit tomorrow that, among other things, brings
Songbird fully into ES6 compliance. Please check back then and let me know
if the new commit resolves your issue. :)

Cheers,
Drew

On Oct 12, 2017 2:46 PM, "Nicholas Yang" <notifications@github.com> wrote:

Getting a very annoying error when trying to use songbird. Basically the
Songbird object is not a constructor. I'm pretty much just using the demo
code with some minor ES6 changes (var to let). Any idea why this is
happening?

   let audioContext = new AudioContext();
    let songbird = new Songbird(audioContext);
    songbird.output.connect(audioContext.destination);
    let dimensions = {
      width : 3.1,
      height : 2.5,
      depth : 3.4
    };
    let materials = {
      left : 'brick-bare',
      right : 'curtain-heavy',
      front : 'marble',
      back : 'glass-thin',
      down : 'grass',
      up : 'transparent'
    };

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/songbird/issues/5>, or mute the thread

**Comment by NicholasLYang** [comment]
Hi Drew,
I fixed my issue, turns out the library is exported as `{ Songbird: {} }` and not just a global Songbird object. Basically just means for ES6 you need to do a named import versus a default import. I appreciate the notice though!

**Comment by drewbitllama** [comment]
Awesome! Let me know whatever cool things you end up doing with the library. :)
